spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ATEMPLATE?serverTimezone-UTC&chracterEncoding=UTF-8
    username: root
    password: mysql606
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# JWT 토큰 관련 key
jwt:
  encrypt-key: fUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v
  encrypt-iv: ShVmYq3t6w9y$B&E
  signing-key: G-KaPdSgVkYp3s6v
