spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/RS?serverTimezone-UTC&chracterEncoding=UTF-8
    username: root
    password: mysql606
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt-encrypt-key: fUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v
jwt-encrypt-iv: ShVmYq3t6w9y$B&E
